### ISSUE TITLE
Help: Adding menu items with custom properties

### ISSUE THREAD

**Issue by farrukhsubhani** [prabhuignoto/vue-dock-menu#10]
You are planning to have icons in menu. I assume this would a property on each item to define an icon or not.

Can we have other custom properties on menu like hidden or a function to define its visibility url to be used when item is passed on selected function with those properties.

This functionality might already be there and if it is it would be good to have an example of some common scenarios like:

1. Attach a url to menu item and set it to open in new tab or window

1. Hide certain menu items or disable them from being selected.

Thanks a lot for such a nice component.

**Comment by prabhuignoto** [comment]
@farrukhsubhani welcome to vue-dock-menu

> You are planning to have icons in menu. I assume this would a property on each item to define an icon or not.

yes this would be a new property on each item.  This should be available in the next major release.

> Can we have other custom properties on menu like hidden or a function to define its visibility url to be used when item is passed on selected function with those properties.

there is already a property `disable`  to disable items on the menu. could you give it a try. Thanks for reporting as this is missing from the documentation.  i will update the doc.

> 1. Attach a url to menu item and set it to open in new tab or window

i am just wondering how often people would use this as a feature and this could be easily managed from the selection handler.

thanks

**Comment by prabhuignoto** [comment]
@farrukhsubhani the component now has full support for icons.  After some pondering, I decided to use slots as this will give better flexibility.

please check out the usage here.
https://github.com/prabhuignoto/vue-dock-menu#-icon-support
