### ISSUE TITLE
npm run error: [vite] Failed to resolve module import.....

### ISSUE THREAD

**Issue by guolaopi** [prabhuignoto/vue-dock-menu#17]
I just run "npm i" and "npm run dev", and it's output: 
"[vite] Failed to resolve module import "vue/dist/vue.runtime.esm-bundler.jsode_modules
uedist
ue.runtime.esm-bundler.js". (imported by /src/App.vue)"
![图片](https://user-images.githubusercontent.com/11360515/102036303-6d050d80-3dfd-11eb-839f-2bc78c42e09b.png)

How can I fix it? thanks.

**Comment by prabhuignoto** [comment]
Let me check it.  Meanwhile can you try running with Yarn

**Comment by guolaopi** [comment]
> 
> 
> Let me check it. Meanwhile can you try running with Yarn

I try use Yarn, but the result has no different:
![图片](https://user-images.githubusercontent.com/11360515/102046598-94b49f80-3e16-11eb-8df6-681a80d6ece0.png)

Do I something did wrong?

1. yarn install
2. yarn run dev

**Comment by prabhuignoto** [comment]
very  strange.  I  tried  doing  a fresh  clone.  Install & run works for me.

Are you running  windows/mac.  is this the first time you are running a project that uses vite?

**Comment by guolaopi** [comment]
> 
> 
> very strange. I tried doing a fresh clone. Install & run works for me.
> 
> Are you running windows/mac. is this the first time you are running a project that uses vite?

Sorry, I forgot my environment:
 System: Windows10 20H2
 Node: 14.9.0
 Npm: 6.14.8

and yes, this is my first time to use vite and vue3.x

**Comment by prabhuignoto** [comment]
hi @guolaopi  can you take a fresh pull and see if this is still happening.

**Comment by guolaopi** [comment]
> 
> 
> hi @guolaopi can you take a fresh pull and see if this is still happening.

It's run without problem now，thanks.

**Comment by prabhuignoto** [comment]
thanks @guolaopi
