### ISSUE TITLE
More than two items with menu will be error.

### ISSUE THREAD

**Issue by lizzyliao** [prabhuignoto/vue-dock-menu#23]
More than two items with menu will be error.
It will show two menus at the same time. 

See as the following picture. 
![image](https://user-images.githubusercontent.com/57212099/104413523-72df4180-55a9-11eb-98f2-e664a80af2db.png)

Did I miss some settings?  Please tell me if I am wrong.  
Thank you very much.

**Comment by prabhuignoto** [comment]
@lizzyliao thanks for reporting the issue.

can you please share the `items` collection used to generate the menu

**Comment by prabhuignoto** [comment]
@lizzyliao this has been fixed with #24 and changes published. please update the lib and let me know if everything outs alright.

**Comment by lizzyliao** [comment]
@prabhuignoto   It works fine.  Thank you very much.  👍
